# Generated by Django 4.2.5 on 2023-09-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='goods_list',
            new_name='goods_in_cart',
        ),
    ]
